// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalSite.Presentation.Api.Data;

#nullable disable

namespace PersonalSite.Presentation.Api.Data.Migrations
{
    [DbContext(typeof(PresentationDbContext))]
    [Migration("20260824191638_EnforceDatabaseInvariants")]
    partial class EnforceDatabaseInvariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("presentation")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("company");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("role");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_experiences");

                    b.ToTable("experiences", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_experiences_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ExperienceHighlight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_experience_highlights");

                    b.HasIndex("ExperienceId")
                        .HasDatabaseName("ix_experience_highlights_experience_id");

                    b.ToTable("experience_highlights", "presentation");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ExperienceTechnology", b =>
                {
                    b.Property<Guid>("ExperienceId")
                        .HasColumnType("uuid")
                        .HasColumnName("experience_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.HasKey("ExperienceId", "TechnologyId")
                        .HasName("pk_experience_technologies");

                    b.HasIndex("TechnologyId")
                        .HasDatabaseName("ix_experience_technologies_technology_id");

                    b.ToTable("experience_technologies", "presentation");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Availability")
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)")
                        .HasColumnName("availability");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("biography");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrentFocus")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("current_focus");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("full_name");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("headline");

                    b.Property<string>("Location")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("location");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<string>("ShortSummary")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("short_summary");

                    b.Property<string>("SingletonKey")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("singleton_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_profiles");

                    b.HasIndex("SingletonKey")
                        .IsUnique()
                        .HasDatabaseName("ix_profiles_singleton_key");

                    b.ToTable("profiles", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_profiles_singleton_key", "singleton_key = 'profile'");

                            t.HasCheckConstraint("ck_profiles_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ProfileSocialLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("profile_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_profile_social_links");

                    b.HasIndex("ProfileId")
                        .HasDatabaseName("ix_profile_social_links_profile_id");

                    b.ToTable("profile_social_links", "presentation");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("ImageAlt")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("image_alt");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("integer")
                        .HasColumnName("image_height");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("image_url");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("integer")
                        .HasColumnName("image_width");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean")
                        .HasColumnName("is_featured");

                    b.Property<string>("LiveUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("live_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<string>("RepositoryUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("repository_url");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.ToTable("projects", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_projects_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ProjectTechnology", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("TechnologyId")
                        .HasColumnType("uuid")
                        .HasColumnName("technology_id");

                    b.HasKey("ProjectId", "TechnologyId")
                        .HasName("pk_project_technologies");

                    b.HasIndex("TechnologyId")
                        .HasDatabaseName("ix_project_technologies_technology_id");

                    b.ToTable("project_technologies", "presentation");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("CategoryId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_category_id_normalized_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("skills", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_skills_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.SkillCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_skill_categories");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_skill_categories_normalized_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("skill_categories", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_skill_categories_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("normalized_name");

                    b.Property<DateTimeOffset>("PublicUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("public_updated_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_technologies");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ix_technologies_normalized_name")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("technologies", "presentation", t =>
                        {
                            t.HasCheckConstraint("ck_technologies_version_positive", "version > 0");
                        });
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ExperienceHighlight", b =>
                {
                    b.HasOne("PersonalSite.Presentation.Api.Data.Experience", null)
                        .WithMany("Highlights")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_experience_highlights_experiences_experience_id");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ExperienceTechnology", b =>
                {
                    b.HasOne("PersonalSite.Presentation.Api.Data.Experience", "Experience")
                        .WithMany("Technologies")
                        .HasForeignKey("ExperienceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_experience_technologies_experiences_experience_id");

                    b.HasOne("PersonalSite.Presentation.Api.Data.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_experience_technologies_technologies_technology_id");

                    b.Navigation("Experience");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ProfileSocialLink", b =>
                {
                    b.HasOne("PersonalSite.Presentation.Api.Data.Profile", null)
                        .WithMany("SocialLinks")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_profile_social_links_profiles_profile_id");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.ProjectTechnology", b =>
                {
                    b.HasOne("PersonalSite.Presentation.Api.Data.Project", "Project")
                        .WithMany("Technologies")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_technologies_projects_project_id");

                    b.HasOne("PersonalSite.Presentation.Api.Data.Technology", "Technology")
                        .WithMany()
                        .HasForeignKey("TechnologyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_project_technologies_technologies_technology_id");

                    b.Navigation("Project");

                    b.Navigation("Technology");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Skill", b =>
                {
                    b.HasOne("PersonalSite.Presentation.Api.Data.SkillCategory", "Category")
                        .WithMany("Skills")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_skills_skill_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Experience", b =>
                {
                    b.Navigation("Highlights");

                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Profile", b =>
                {
                    b.Navigation("SocialLinks");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.Project", b =>
                {
                    b.Navigation("Technologies");
                });

            modelBuilder.Entity("PersonalSite.Presentation.Api.Data.SkillCategory", b =>
                {
                    b.Navigation("Skills");
                });
#pragma warning restore 612, 618
        }
    }
}
